version: '2'

services:

  web:
    image: hitalos/laravel:latest
    ports:
        - 8088:80
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: crstats
        DB_USERNAME: root
        DB_PASSWORD: password
        DB_CONNECTION: pgsql
    networks:
      - dev-network

  db:
    image: postgres:11
    ports:
        - 5432:5432
    volumes:
        - ./.docker/db/postgresql:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: crstats
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
