version: '2'

services:

    web:
        image: hitalos/laravel:latest
        ports:
            - 8088:80
        volumes:
            - ./:/var/www
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge
