version: '2'

services:

    web:
        image: hitalos/laravel:latest
        ports:
            - 8088:80
        volumes:
            - ./:/var/www
        networks:
            - dev-network

    nginx:
        image: nginx:1.15-alpine
        ports:
            - "81:80"
            - "444:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

networks:
    dev-network:
        driver: bridge
